# As we use Squash `Squash and merge` for the PR merging rule, the PR title validation only needed.
titleOnly: true

# You can override the valid types
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
  - release # our original type
