version: 2.1

jobs:
  # All checks on the codebase that can run in parallel to build_shared_library
  sanity:
    docker:
      - image: circleci/rust:1.50.0-buster
    steps:
      - checkout
      - run:
          name: Install shellcheck
          command: sudo apt install shellcheck
      - run:
          name: Show version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Add Rust components
          command: rustup component add clippy rustfmt
      - restore_cache:
          keys:
            - cargocache-v2-sanity-rust:1.50.0-{{ checksum "Cargo.lock" }}
      - run:
          name: Check formatting
          command: cargo fmt -- --check
      - run:
          name: Run linter
          command: cargo clippy -- -D warnings
      - run:
          name: Run unit tests
          command: cargo test
      - run:
          name: Build docs
          command: cargo doc --no-deps
      - run:
          name: Test docs
          command: |
            sed -i  '/^crate-type = \["cdylib"\]/d' Cargo.toml
            cargo test --doc
      - run:
          name: Run shellcheck
          command: find . -name "*.sh" -exec shellcheck {} +
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/release/.fingerprint
            - target/release/build
            - target/release/deps
          key: cargocache-v2-sanity-rust:1.50.0-{{ checksum "Cargo.lock" }}

  build_shared_library:
    docker:
      - image: circleci/rust:1.50.0-buster
    steps:
      - checkout
      - run:
          name: Show version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - cargocache-v2-build_shared_library-rust:1.50.0-{{ checksum "Cargo.lock" }}
      - run:
          name: Create release build of libwasmvm
          command: make build-rust
      - persist_to_workspace:
          root: ./api
          paths:
            - libwasmvm.so
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/release/.fingerprint
            - target/release/build
            - target/release/deps
          key: cargocache-v2-build_shared_library-rust:1.50.0-{{ checksum "Cargo.lock" }}

  test:
    working_directory: /go/src/github.com/CosmWasm/wasmvm
    docker:
      - image: circleci/golang:1.15
    environment:
      GORACE: "halt_on_error=1"
      BUILD_VERSION: $(echo ${CIRCLE_SHA1} | cut -c 1-10)
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/builds
      - run: cp /tmp/builds/libwasmvm.so ./api
      - run:
          name: Go integration tests
          command: make test
      - run:
          name: Go tests with cgo and race condition safety checks
          command: make test-safety
      - run: make build-go

  test_alpine_build:
    machine:
      image: ubuntu-1604:202010-01
    steps:
      - checkout
      - run: make test-alpine
      - run:
          name: Debug build results
          command: ls -l ./api

  deploy_to_git:
    machine:
      image: ubuntu-1604:202010-01
    steps:
      - add_ssh_keys:
          fingerprints:
            # Custom read/write deployment key with private key stored on CircleCI
            # (see https://app.circleci.com/settings/project/github/CosmWasm/wasmvm/ssh and https://github.com/CosmWasm/wasmvm/settings/keys)
            - "31:de:e5:84:1b:12:81:94:aa:06:50:c0:cb:bd:79:f0"
      - checkout
      - run:
          name: Build shared library for Linux
          command: make release-build-linux
      - run:
          name: Build shared library for macOS
          command: make release-build-macos
      - run:
          name: Debug build results
          command: ls -l ./api
      - run:
          name: Configure git user
          # This is not a GitHub user and no permissions can be configured other than "push access", which
          # we can configure for Deploy keys at https://github.com/CosmWasm/wasmvm/settings/keys
          command: |
            git config user.email "wasmvm@circleci.confio.example.com"
            git config user.name "Deployer"
      - run:
          name: Check-in and push new libraries
          command: |
            git status
            git add ./api
            git commit --allow-empty -m '[skip ci] Built release libraries'
            git push origin $CIRCLE_BRANCH

  build_static_lib:
    machine:
      image: ubuntu-1604:202010-01
    steps:
      - checkout
      - run:
          name: Build static library for Alpine
          command: make release-build-alpine
      - run:
          name: Debug build results
          command: ls -l ./api
      - run:
          name: Collect artifacts
          command: |
            mkdir artifacts
            cp ./api/libwasmvm_muslc.a artifacts
      - run:
          name: Create checksums
          working_directory: artifacts
          command: sha256sum * > checksums.txt && cat checksums.txt
      - store_artifacts:
          path: artifacts
      # Deploy to GitHub releases on tag builds
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Install ghr
                command: |
                  go get github.com/tcnksm/ghr
                  ghr --version
            - run:
                name: Publish artifacts on GitHub
                command: |
                  TAG="$CIRCLE_TAG"
                  TITLE="$TAG"
                  BODY="Build artifacts generated at this tag."
                  ghr -t "$GITHUB_TOKEN" \
                    -u "$CIRCLE_PROJECT_USERNAME" -r "$CIRCLE_PROJECT_REPONAME" \
                    -c "$CIRCLE_SHA1" \
                    -n "$TITLE" -b "$BODY" \
                    -delete \
                    "$TAG" ./artifacts/

workflows:
  version: 2
  build_and_test:
    jobs:
      - sanity
      - build_shared_library:
          filters: # required since other jobs with tag filters require this one
            tags:
              only: /.*/
      - test:
          requires:
            - build_shared_library
      - build_static_lib:
          requires:
            - build_shared_library
          filters:
            # tags and branches are OR combined
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+.*/
            branches:
              only:
                # long living branches
                - main
                - 0.14-dev
      # This is long running, so only double-check on merge commits
      # ensures that all code works on alpine linux
      - test_alpine_build:
          filters:
            tags:
              ignore:
                - /.*/
            branches:
              only:
                # long living branches
                - main
                - 0.14-dev
      # Run only on main, not on tags (auto-build on merge PR)
      - deploy_to_git:
          requires:
            - sanity
            - test
          filters:
            tags:
              ignore:
                - /.*/
            branches:
              only:
                - main
