name: Release

on:
  push:
    branches:
      - main
      - hotfix**

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get-version: # emit package version using `cargo tree -i`
    name: Get Package Version
    runs-on: ubuntu-latest
    outputs:
      package-version: ${{ steps.get-package-version.outputs.version }}
      latest-tag: ${{ steps.get-latest-tag.outputs.tag }}
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.57.0
          profile: minimal
          override: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get latest tag
        id: get-latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1
      - name: Get package version
        id: get-package-version
        working-directory: ./libwasmvm
        run: |
          VERSION=$(cargo tree -i wasmvm | grep -oE "[0-9]+(\.[0-9]+){2}-[0-9]+(\.[0-9]+){2}")
            echo ::set-output name=version::v$VERSION
  push-tag: # if the version does not exist as git tag, push it
    name: Push Tag
    needs:
      - get-version
    if: ${{ needs.get-version.outputs.package-version != needs.get-version.outputs.latest-tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Push Tag to GitHub
        run: |
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
          -d "{\"ref\": \"refs/tags/${{ needs.get-version.outputs.package-version }}\", \"sha\": \"${GITHUB_SHA}\"}" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs"
