name: Release

on:
  push:
    branches:
      - main
      - hotfix**

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  get-version: # emit package version using `cargo tree -i`
    name: Get Package Version
    runs-on: ubuntu-latest
    outputs:
      package-version: ${{ steps.get-package-version.outputs.version }}
      latest-tag: ${{ steps.get-latest-tag.outputs.tag }}
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.57.0
          profile: minimal
          override: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get latest tag
        id: get-latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1
      - name: Get package version
        id: get-package-version
        working-directory: ./libwasmvm
        run: |
          VERSION=$(cargo tree -i wasmvm | grep -oE "[0-9]+(\.[0-9]+){2}-[0-9]+(\.[0-9]+){2}")
            echo ::set-output name=version::v$VERSION

  build_static_lib:
    name: Build static libraries
    needs:
      - get-version
    if: ${{ needs.get-version.outputs.package-version != needs.get-version.outputs.latest-tag }}
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/setup-go@v3.2.1
        with:
          go-version: 1.18
        id: go
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: cd builders && make docker-image-alpine
      - name: Build & Test static library
        run: make release-build-alpine
      - name: Collect artifacts
        run: |
          mkdir artifacts
          cp ./api/libwasmvm_muslc.a artifacts/libwasmvm_muslc.x86_64.a
          cp ./api/libwasmvm_muslc.aarch64.a artifacts/libwasmvm_muslc.aarch64.a
      - name: Create checksums
        working-directory: artifacts
        run: sha256sum * > checksums.txt && cat checksums.txt
      - name: Upload static library
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./artifacts

  push-tag: # if the version does not exist as git tag, push it
    name: Push Tag
    needs:
      - get-version
    if: ${{ needs.get-version.outputs.package-version != needs.get-version.outputs.latest-tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Push Tag to GitHub
        run: |
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
          -d "{\"ref\": \"refs/tags/${{ needs.get-version.outputs.package-version }}\", \"sha\": \"${GITHUB_SHA}\"}" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs"

  update-releases:
    name: Update Latest release
    needs:
      - push-tag
      - build_static_lib
    if: ${{ needs.get-version.outputs.package-version != needs.get-version.outputs.latest-tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.get-version.outputs.package-version }}
          body: ${{ github.event.pull_request.body }}
          files: |
            ./artifacts/*
          draft: false
          prerelease: false
